[project]
name = "datascience"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "lxml==5.4.0",
    "notebook>=7.4.1",
    "numpy>=2.2.5",
    "openpyxl==3.1.5",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
